INSERT INTO public.books (name, title) VALUES ('genesis', 'Génesis');
INSERT INTO public.books (name, title) VALUES ('exodo', 'Éxodo');
INSERT INTO public.books (name, title) VALUES ('levitico', 'Levítico');
INSERT INTO public.books (name, title) VALUES ('numeros', 'Números');
INSERT INTO public.books (name, title) VALUES ('deuteronomio', 'Deuteronomio');
INSERT INTO public.books (name, title) VALUES ('josue', 'Josué');
INSERT INTO public.books (name, title) VALUES ('jueces', 'Jueces');
INSERT INTO public.books (name, title) VALUES ('rut', 'Rut');
INSERT INTO public.books (name, title) VALUES ('1-samuel', '1 Samuel');
INSERT INTO public.books (name, title) VALUES ('2-samuel', '2 Samuel');
INSERT INTO public.books (name, title) VALUES ('1-reyes', '1 Reyes');
INSERT INTO public.books (name, title) VALUES ('2-reyes', '2 Reyes');
INSERT INTO public.books (name, title) VALUES ('1-cronicas', '1 Crónicas');
INSERT INTO public.books (name, title) VALUES ('2-cronicas', '2 Crónicas');
INSERT INTO public.books (name, title) VALUES ('esdras', 'Esdras');
INSERT INTO public.books (name, title) VALUES ('nehemias', 'Nehemías');
INSERT INTO public.books (name, title) VALUES ('ester', 'Ester');
INSERT INTO public.books (name, title) VALUES ('job', 'Job');
INSERT INTO public.books (name, title) VALUES ('salmos', 'Salmos');
INSERT INTO public.books (name, title) VALUES ('proverbios', 'Proverbios');
INSERT INTO public.books (name, title) VALUES ('eclesiastes', 'Eclesiastés');
INSERT INTO public.books (name, title) VALUES ('cantares', 'Cantares');
INSERT INTO public.books (name, title) VALUES ('isaias', 'Isaías');
INSERT INTO public.books (name, title) VALUES ('jeremias', 'Jeremías');
INSERT INTO public.books (name, title) VALUES ('lamentaciones', 'Lamentaciones');
INSERT INTO public.books (name, title) VALUES ('ezequiel', 'Ezequiel');
INSERT INTO public.books (name, title) VALUES ('daniel', 'Daniel');
INSERT INTO public.books (name, title) VALUES ('oseas', 'Oseas');
INSERT INTO public.books (name, title) VALUES ('joel', 'Joel');
INSERT INTO public.books (name, title) VALUES ('amos', 'Amós');
INSERT INTO public.books (name, title) VALUES ('abdias', 'Abdías');
INSERT INTO public.books (name, title) VALUES ('jonas', 'Jonás');
INSERT INTO public.books (name, title) VALUES ('miqueas', 'Miqueas');
INSERT INTO public.books (name, title) VALUES ('nahum', 'Nahum');
INSERT INTO public.books (name, title) VALUES ('habacuc', 'Habacuc');
INSERT INTO public.books (name, title) VALUES ('sofonias', 'Sofonías');
INSERT INTO public.books (name, title) VALUES ('hageo', 'Hageo');
INSERT INTO public.books (name, title) VALUES ('zacarias', 'Zacarías');
INSERT INTO public.books (name, title) VALUES ('malaquias', 'Malaquías');
INSERT INTO public.books (name, title) VALUES ('mateo', 'Mateo');
INSERT INTO public.books (name, title) VALUES ('marcos', 'Marcos');
INSERT INTO public.books (name, title) VALUES ('lucas', 'Lucas');
INSERT INTO public.books (name, title) VALUES ('juan', 'Juan');
INSERT INTO public.books (name, title) VALUES ('hechos', 'Hechos');
INSERT INTO public.books (name, title) VALUES ('romanos', 'Romanos');
INSERT INTO public.books (name, title) VALUES ('1-corintios', '1 Corintios');
INSERT INTO public.books (name, title) VALUES ('2-corintios', '2 Corintios');
INSERT INTO public.books (name, title) VALUES ('galatas', 'Gálatas');
INSERT INTO public.books (name, title) VALUES ('efesios', 'Efesios');
INSERT INTO public.books (name, title) VALUES ('filipenses', 'Filipenses');
INSERT INTO public.books (name, title) VALUES ('colosenses', 'Colosenses');
INSERT INTO public.books (name, title) VALUES ('1-tesalonicenses', '1 Tesalonicenses');
INSERT INTO public.books (name, title) VALUES ('2-tesalonicenses', '2 Tesalonicenses');
INSERT INTO public.books (name, title) VALUES ('1-timoteo', '1 Timoteo');
INSERT INTO public.books (name, title) VALUES ('2-timoteo', '2 Timoteo');
INSERT INTO public.books (name, title) VALUES ('tito', 'Tito');
INSERT INTO public.books (name, title) VALUES ('filemon', 'Filemón');
INSERT INTO public.books (name, title) VALUES ('hebreos', 'Hebreos');
INSERT INTO public.books (name, title) VALUES ('santiago', 'Santiago');
INSERT INTO public.books (name, title) VALUES ('1-pedro', '1 Pedro');
INSERT INTO public.books (name, title) VALUES ('2-pedro', '2 Pedro');
INSERT INTO public.books (name, title) VALUES ('1-juan', '1 Juan');
INSERT INTO public.books (name, title) VALUES ('2-juan', '2 Juan');
INSERT INTO public.books (name, title) VALUES ('3-juan', '3 Juan');
INSERT INTO public.books (name, title) VALUES ('judas', 'Judas');
INSERT INTO public.books (name, title) VALUES ('apocalipsis', 'Apocalipsis');
