#!/usr/bin/env python3
import json
import os
import re
import sys
import urllib.request
from urllib.parse import quote_plus


ROOT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
FONTS_JSON = os.path.join(ROOT_DIR, "scripts", "fonts.json")
FONTS_OUT_DIR = os.path.join(ROOT_DIR, "apps", "web", "public", "fonts")
FONTS_CSS_PATH = os.path.join(ROOT_DIR, "apps", "web", "src", "fonts.css")
FONT_OPTIONS_TS = os.path.join(ROOT_DIR, "apps", "web", "src", "constants", "fontOptions.ts")


USER_AGENT = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 13_5_0) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/120.0.0.0 Safari/537.36"
)

WEIGHTS = "0,300;0,400;0,500;0,600;0,700;1,400;1,600"


def slugify(name: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9]+", "-", name.strip().lower())
    return slug.strip("-")


def fetch_text(url: str) -> str:
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(req) as resp:
        return resp.read().decode("utf-8")


def fetch_binary(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(req) as resp:
        return resp.read()


def ensure_dir(path: str) -> None:
    os.makedirs(path, exist_ok=True)


def build_google_fonts_url(family: str) -> str:
    family_param = quote_plus(family)
    return f"https://fonts.googleapis.com/css2?family={family_param}:ital,wght@{WEIGHTS}&display=swap"


def rewrite_css_and_download(css: str, family: str, family_dir: str) -> str:
    pattern = re.compile(
        r"url\((?P<quote>['\"]?)(?P<url>(?:https?:)?//fonts\.gstatic\.com/[^)'\"]+)(?P=quote)\)"
    )
    rewritten = css
    matches = list(pattern.finditer(css))
    if not matches:
        print(f"Warning: no font URLs found for {family}", file=sys.stderr)
        return rewritten

    for match in matches:
        raw_url = match.group("url")
        fetch_url = f"https:{raw_url}" if raw_url.startswith("//") else raw_url
        filename = fetch_url.split("/")[-1].split("?")[0]
        local_rel = f"/fonts/{family_dir}/{filename}"
        local_path = os.path.join(FONTS_OUT_DIR, family_dir, filename)
        if not os.path.exists(local_path):
            data = fetch_binary(fetch_url)
            with open(local_path, "wb") as f:
                f.write(data)
        rewritten = rewritten.replace(raw_url, local_rel)
    return rewritten


def generate_font_options_ts(families: list[str]) -> None:
    ensure_dir(os.path.dirname(FONT_OPTIONS_TS))
    lines = [
        "export const fontOptions = [",
    ]
    for family in families:
        lines.append(f'  "{family}",')
    lines.append("] as const;")
    lines.append("")
    lines.append("export type FontOption = (typeof fontOptions)[number];")
    content = "\n".join(lines)
    with open(FONT_OPTIONS_TS, "w", encoding="utf-8") as f:
        f.write(content)


def main() -> int:
    if not os.path.exists(FONTS_JSON):
        print(f"Missing {FONTS_JSON}", file=sys.stderr)
        return 1

    with open(FONTS_JSON, "r", encoding="utf-8") as f:
        data = json.load(f)

    families = data.get("families", [])
    if not families:
        print("No families found in fonts.json", file=sys.stderr)
        return 1

    ensure_dir(FONTS_OUT_DIR)
    css_chunks = ["/* Generated by scripts/fetch-fonts.py */", ""]

    for family in families:
        family_dir = slugify(family)
        ensure_dir(os.path.join(FONTS_OUT_DIR, family_dir))
        url = build_google_fonts_url(family)
        try:
            css = fetch_text(url)
        except Exception as err:
            print(f"Failed to fetch CSS for {family}: {err}", file=sys.stderr)
            return 1

        try:
            rewritten = rewrite_css_and_download(css, family, family_dir)
        except Exception as err:
            print(f"Failed to download fonts for {family}: {err}", file=sys.stderr)
            return 1

        css_chunks.append(f"/* {family} */")
        css_chunks.append(rewritten.strip())
        css_chunks.append("")

    with open(FONTS_CSS_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(css_chunks).strip() + "\n")

    generate_font_options_ts(families)
    print(f"Downloaded {len(families)} font families.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
