package consts

var Books = map[string]string{
	"genesis":          "Génesis",
	"exodo":            "Éxodo",
	"levitico":         "Levítico",
	"numeros":          "Números",
	"deuteronomio":     "Deuteronomio",
	"josue":            "Josué",
	"jueces":           "Jueces",
	"rut":              "Rut",
	"1-samuel":         "1 Samuel",
	"2-samuel":         "2 Samuel",
	"1-reyes":          "1 Reyes",
	"2-reyes":          "2 Reyes",
	"1-cronicas":       "1 Crónicas",
	"2-cronicas":       "2 Crónicas",
	"esdras":           "Esdras",
	"nehemias":         "Nehemías",
	"ester":            "Ester",
	"job":              "Job",
	"salmos":           "Salmos",
	"proverbios":       "Proverbios",
	"eclesiastes":      "Eclesiastés",
	"cantares":         "Cantares",
	"isaias":           "Isaías",
	"jeremias":         "Jeremías",
	"lamentaciones":    "Lamentaciones",
	"ezequiel":         "Ezequiel",
	"daniel":           "Daniel",
	"oseas":            "Oseas",
	"joel":             "Joel",
	"amos":             "Amós",
	"abdias":           "Abdías",
	"jonas":            "Jonás",
	"miqueas":          "Miqueas",
	"nahum":            "Nahum",
	"habacuc":          "Habacuc",
	"sofonias":         "Sofonías",
	"hageo":            "Hageo",
	"zacarias":         "Zacarías",
	"malaquias":        "Malaquías",
	"mateo":            "Mateo",
	"marcos":           "Marcos",
	"lucas":            "Lucas",
	"juan":             "Juan",
	"hechos":           "Hechos",
	"romanos":          "Romanos",
	"1-corintios":      "1 Corintios",
	"2-corintios":      "2 Corintios",
	"galatas":          "Gálatas",
	"efesios":          "Efesios",
	"filipenses":       "Filipenses",
	"colosenses":       "Colosenses",
	"1-tesalonicenses": "1 Tesalonicenses",
	"2-tesalonicenses": "2 Tesalonicenses",
	"1-timoteo":        "1 Timoteo",
	"2-timoteo":        "2 Timoteo",
	"tito":             "Tito",
	"filemon":          "Filemón",
	"hebreos":          "Hebreos",
	"santiago":         "Santiago",
	"1-pedro":          "1 Pedro",
	"2-pedro":          "2 Pedro",
	"1-juan":           "1 Juan",
	"2-juan":           "2 Juan",
	"3-juan":           "3 Juan",
	"judas":            "Judas",
	"apocalipsis":      "Apocalipsis",
}
