import type { CoverDocument } from "../types/cover-design";
import type { SermonCover } from "../services/covers";

export const buildLegacyCoverDoc = (cover: SermonCover): CoverDocument => ({
  canvas: {
    width: 1920,
    height: 1080,
    safeArea: 80,
    preset: "16:9",
    background: cover.background
      ? {
          type: "image",
          src: cover.background,
          fit: "cover",
          opacity: 1,
          positionX: 50,
          positionY: 50,
          scale: 1,
          blur: 0,
          vignette: 0,
          overlayColor: cover.settings?.backgroundTint ?? "#000000",
          overlayOpacity: 0.6,
        }
      : {
        type: "solid",
        color: cover.settings?.backgroundTint ?? "#000000",
      },
  },
  layers: [
    {
      id: "legacy-date",
      type: "text",
      role: "date",
      name: "Fecha",
      x: 160,
      y: 140,
      width: 600,
      height: 50,
      text: cover.dateLabel || "",
      style: {
        fontFamily: cover.settings?.fontFamily ?? "Space Grotesk",
        fontSize: 18,
        fontWeight: 500,
        color: "rgba(255,255,255,0.7)",
        align: cover.settings?.align ?? "left",
        letterSpacing: 4,
      },
    },
    {
      id: "legacy-badge",
      type: "badge",
      role: "badge",
      name: "Badge",
      x: 160,
      y: 200,
      width: 220,
      height: 60,
      text: cover.settings?.badgeLabel ?? "",
      style: {
        fontFamily: cover.settings?.fontFamily ?? "Space Grotesk",
        fontSize: 18,
        fontWeight: 700,
        color: "#0f172a",
        background: cover.settings?.accentColor ?? "#22c55e",
        radius: 999,
        letterSpacing: 3,
      },
    },
    {
      id: "legacy-title",
      type: "text",
      role: "title",
      name: "Título",
      x: 160,
      y: 340,
      width: 1600,
      height: 180,
      text: cover.title,
      style: {
        fontFamily: cover.settings?.fontFamily ?? "Space Grotesk",
        fontSize: cover.settings?.titleSize ?? 54,
        fontWeight: 700,
        color: cover.settings?.titleColor ?? "#ffffff",
        align: cover.settings?.align ?? "left",
        lineHeight: 1.1,
      },
    },
    {
      id: "legacy-subtitle",
      type: "text",
      role: "subtitle",
      name: "Subtítulo",
      x: 160,
      y: 520,
      width: 1400,
      height: 120,
      text: cover.subtitle,
      style: {
        fontFamily: cover.settings?.fontFamily ?? "Space Grotesk",
        fontSize: cover.settings?.subtitleSize ?? 26,
        fontWeight: 500,
        color: cover.settings?.subtitleColor ?? "#e2e8f0",
        align: cover.settings?.align ?? "left",
        lineHeight: 1.2,
      },
    },
    {
      id: "legacy-speaker",
      type: "text",
      role: "speaker",
      name: "Predicador",
      x: 160,
      y: 690,
      width: 800,
      height: 80,
      text: cover.speaker,
      style: {
        fontFamily: cover.settings?.fontFamily ?? "Space Grotesk",
        fontSize: 26,
        fontWeight: 600,
        color: "#ffffff",
        align: cover.settings?.align ?? "left",
        letterSpacing: 4,
      },
    },
  ],
});
