// Code generated by MockGen. DO NOT EDIT.
// Source: ./bible.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	entities "ionic-x-ms/domain/entities"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockBibleActionInterface is a mock of BibleActionInterface interface.
type MockBibleActionInterface struct {
	ctrl     *gomock.Controller
	recorder *MockBibleActionInterfaceMockRecorder
}

// MockBibleActionInterfaceMockRecorder is the mock recorder for MockBibleActionInterface.
type MockBibleActionInterfaceMockRecorder struct {
	mock *MockBibleActionInterface
}

// NewMockBibleActionInterface creates a new mock instance.
func NewMockBibleActionInterface(ctrl *gomock.Controller) *MockBibleActionInterface {
	mock := &MockBibleActionInterface{ctrl: ctrl}
	mock.recorder = &MockBibleActionInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBibleActionInterface) EXPECT() *MockBibleActionInterfaceMockRecorder {
	return m.recorder
}

// GetBibleReferences mocks base method.
func (m *MockBibleActionInterface) GetBibleReferences(ctx context.Context, request entities.RequestBible) (*entities.Chapter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBibleReferences", ctx, request)
	ret0, _ := ret[0].(*entities.Chapter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBibleReferences indicates an expected call of GetBibleReferences.
func (mr *MockBibleActionInterfaceMockRecorder) GetBibleReferences(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBibleReferences", reflect.TypeOf((*MockBibleActionInterface)(nil).GetBibleReferences), ctx, request)
}

// SearchVerses mocks base method.
func (m *MockBibleActionInterface) SearchVerses(ctx context.Context, terms []string, version int, limit int) ([]entities.VerseMatch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchVerses", ctx, terms, version, limit)
	ret0, _ := ret[0].([]entities.VerseMatch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchVerses indicates an expected call of SearchVerses.
func (mr *MockBibleActionInterfaceMockRecorder) SearchVerses(ctx, terms, version, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchVerses", reflect.TypeOf((*MockBibleActionInterface)(nil).SearchVerses), ctx, terms, version, limit)
}

// VerifyBibleReference mocks base method.
func (m *MockBibleActionInterface) VerifyBibleReference(ctx context.Context, request entities.RequestBible) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyBibleReference", ctx, request)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyBibleReference indicates an expected call of VerifyBibleReference.
func (mr *MockBibleActionInterfaceMockRecorder) VerifyBibleReference(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyBibleReference", reflect.TypeOf((*MockBibleActionInterface)(nil).VerifyBibleReference), ctx, request)
}
